# -*- coding: utf-8 -*-
"""concrete_strength_predictive_analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mqy_6Lp9jBx8I9GoKqNYrXXsr0rt-EP3

# Setup

## Install ucimlrepo package to load the dataset
"""

!pip install ucimlrepo

"""## Import Libraries"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import matplotlib.pyplot as plt
# %matplotlib inline
import numpy as np

"""## Data Loading
- dataset link: [click here!](https://archive.ics.uci.edu/dataset/165/concrete+compressive+strength)
- ucirepo has a fetch method that returns a pandas dataframe of the dataset called fetch_ucirepo(id)
- to get the dataset id
  * go to the dataset link
  * click the "import in python" button and copy the code in python notebook
  * or check the url after the word "dataset/"

- ucirepo returns the dataset at data object
- inside the data object listed the features, targets, and original
"""

from ucimlrepo import fetch_ucirepo
concrete_compressive_strength = fetch_ucirepo(id=165)

concrete_data = concrete_compressive_strength.data.original
concrete_data

"""### Split the features and label"""

X = concrete_compressive_strength.data.features
y = concrete_compressive_strength.data.targets

"""# Data Understanding

Download dataset
- dataset link: [click here!](https://archive.ics.uci.edu/dataset/165/concrete+compressive+strength)

## EDA - Variable Description

Variable Description
* Features : the component used for the concrete mixture
    1. Cement (component 1): Numerical value representing the amount of cement in kilograms in a cubic meter mixture.
    2. Blast Furnace Slag (component 2): Numerical value representing the amount of blast furnace slag in kilograms in a cubic meter mixture.
    3. Fly Ash (component 3): Numerical value representing the amount of fly ash in kilograms in a cubic meter mixture.
    4. Water (component 4): Numerical value representing the amount of water in kilograms in a cubic meter mixture.
    5. Superplasticizer (component 5): Numerical value representing the amount of superplasticizer in kilograms in a cubic meter mixture.
    6. Coarse Aggregate (component 6): Numerical value representing the amount of coarse aggregate in kilograms in a cubic meter mixture.
    7. Fine Aggregate (component 7): Numerical value representing the amount of fine aggregate in kilograms in a cubic meter mixture.
    8. Age: Numerical value representing the age of the concrete in days (1 to 365).

* Target:
  - Concrete Compressive Strength: Numerical value representing the compressive strength of the concrete in megapascals (MPa).

### Check dataset sample
"""

concrete_data.info()

"""### Check for missing values
> note: the 0's means that component wasn't used for the mixture
"""

concrete_data.describe()

blast = (concrete_data['Blast Furnace Slag'] == 0).sum()
fly = (concrete_data['Fly Ash'] == 0).sum()
sup = (concrete_data['Superplasticizer'] == 0).sum()

print("Nilai 0 di kolom Blast Furnace Slag ada: ",blast)
print("Nilai 0 di kolom Fly Ash ada: ",fly)
print("Nilai 0 di kolom Superplasticizer ada: ",sup)